- name: configure sshd
  copy: src=files/sshd_config dest=/etc/ssh/sshd_config
  notify: restart sshd service
  tags: sshd

- name: install screen
  apt: name=screen update_cache=yes
  tags: apt

- name: detect architecture
  shell: uname -m
  register: arch
  failed_when: arch.rc != 0

- include: mackerel-agent_apt.yml
  when: arch.stdout != 'arm'

- include: mackerel-agent_arm.yml
  when: arch.stdout == 'arm'
