- name: register docker apt respository
  copy: src=files/docker.list dest=/etc/apt/sources.list.d/docker.list
  tags: docker

- name: register docker apt repository gpg key
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  tags: docker

- name: install docker
  apt: name=docker-engine update_cache=yes
  tags: docker

- name: configure docker service
  copy: src=files/docker.service dest=/lib/systemd/system/docker.service
  notify: restart docker service
  tags: docker

- name: enable docker service
  service: name=docker enabled=yes state=started
  tags: docker

- name: install pip
  package: name=python-pip
  tags: datadog

- name: install docker-py
  pip: name=docker-py
  tags: datadog

- name: pull dd-agent docker image
  docker_image: name=datadog/docker-dd-agent
  tags: datadog
